In [16]:
import pandas as pd

In [17]:
df_h=pd.read_csv('../../data/homology/csv_files/high_data_filter.csv')
df_m=pd.read_csv('../../data/homology/csv_files/medium_data_filter.csv')
df_l=pd.read_csv('../../data/homology/csv_files/low_data_filter.csv')
df=pd.read_csv('../../data/not_outliers/notout_antiviral.csv')

In [18]:
df_Q1=pd.read_csv('../../data/homology/csv_files/df_low_Q1_data_filter.csv')
df_Q2=pd.read_csv('../../data/homology/csv_files/df_low_Q2_data_filter.csv')
df_Q3=pd.read_csv('../../data/homology/csv_files/df_low_Q3_data_filter.csv')
df_Q4=pd.read_csv('../../data/homology/csv_files/df_low_Q4_data_filter.csv')

In [19]:
name='antiviral_homology_90'

In [20]:
df_all=pd.concat([df_h, df_m, df_l], axis=0)
df_all_Q=pd.concat([df_Q1, df_Q2, df_Q3, df_Q4], axis=0)

In [21]:
df

,sequence,experimental_characteristics,half_life_seconds,length_sequence,target
0,AAAMSQVTN,Mammalian,15840.0,9,1
1,AACEVAKNLNESLIDLQELGKYEQYIKW,Mammalian,15840.0,28,1
2,AAGAVVNDL,Mammalian,15840.0,9,1
3,AAHLIDALYAEFLGGRVLTT,Mammalian,15840.0,20,1
4,AAHLIDALYAEFLGGRVLTTPVVHRALFYASAVLRQPFLAGVPSA,Mammalian,15840.0,45,1
...,...,...,...,...,...
1924,YVREHGVPIHADKYFEQVLK,Mammalian,10080.0,20,1
1925,YWILEYLWKVPFDFWRGV,E_coli,7200.0,18,0
1926,YWILEYLWKVPFDFWRGV,Mammalian,10080.0,18,1
1927,YWILEYLWKVPFDFWRGV,Yeast,36000.0,18,2
1928,YAGAVVNDL,E_coli,7200.0,9,0

In [22]:
df_all['sequence'].unique().shape

(623,)

In [23]:
df_all_Q['sequence'].unique().shape

(474,)

In [24]:
filtered_df = df[df['sequence'].isin(df_all['sequence'])]
filtered_df

,sequence,experimental_characteristics,half_life_seconds,length_sequence,target
0,AAAMSQVTN,Mammalian,15840.0,9,1
1,AACEVAKNLNESLIDLQELGKYEQYIKW,Mammalian,15840.0,28,1
2,AAGAVVNDL,Mammalian,15840.0,9,1
4,AAHLIDALYAEFLGGRVLTTPVVHRALFYASAVLRQPFLAGVPSA,Mammalian,15840.0,45,1
5,AAKAWKKAKAWKKAKWWKKAA,Mammalian,15840.0,21,1
...,...,...,...,...,...
1924,YVREHGVPIHADKYFEQVLK,Mammalian,10080.0,20,1
1925,YWILEYLWKVPFDFWRGV,E_coli,7200.0,18,0
1926,YWILEYLWKVPFDFWRGV,Mammalian,10080.0,18,1
1927,YWILEYLWKVPFDFWRGV,Yeast,36000.0,18,2
1928,YAGAVVNDL,E_coli,7200.0,9,0

In [25]:
filtered_df.value_counts('target')

target
0    678
1    437
2    198
dtype: int64

In [26]:
low=df[df['target'] == 0]

In [27]:
filtered_df_Q = low[low['sequence'].isin(df_all_Q['sequence'])]

In [28]:
filtered_df_Q

,sequence,experimental_characteristics,half_life_seconds,length_sequence,target
103,CAVACELKWESEFWRWTE,Mammalian,4320.0,18,0
104,CDVIALLACHLNT,Mammalian,4320.0,13,0
107,CDVIALLCHLNTPSFNTTHYRESWY,Mammalian,4320.0,25,0
108,CEEIRARLSTHLRKMRKRLMRDADDLQKRLAVY,Mammalian,4320.0,33,0
109,CEELRVRLASHLRKLRKRLLRDADDLQKRLAVY,Mammalian,4320.0,33,0
...,...,...,...,...,...
1855,YQVVKQPDYLLVPEEVMEYK,E_coli,7200.0,20,0
1862,YRWWRWARRWYRWWRWARRW,E_coli,7200.0,20,0
1865,YTMLVVDDL,E_coli,7200.0,9,0
1869,YTSLIHSLIEEAQNQQEKNEQELLELDKWASLWNWF,E_coli,7200.0,36,0
1922,YVREHGVPIHADKYFEQVLK,E_coli,7200.0,20,0

In [29]:
filtered_df_Q=filtered_df_Q.drop(columns=['target'])
filtered_df_Q=filtered_df_Q.rename(columns={'half_life_seconds': 'target'})

In [30]:
#filtered_df.to_csv("../data/all/antiviral_filtered.csv", index=False)
#filtered_df=filtered_df.filter(items=['sequence', 'experimental_characteristics', 'target'])
filtered_df.to_csv(f"../../data/{name}.csv", index=False)
filtered_df_Q.to_csv(f"../../data/{name}_Q.csv", index=False)